Allow also assigning a public ip for ssh tunnel
AOEpeople/StackFormation pull request #44
Opened 2016-11-08 13:20 UTC by Dakumo

2016-11-09 20:26 UTC, kj187 requested changes

2016-11-09 20:26 UTC, kj187 commented on src/AwsInspector/Ssh/Connection.php
> +        if (count(explode(':', $configuration)) == 4) {
I see the explode function 3 times, independently of the condition the same explode will always be executed twice. You can do that once and assign the result in a variable ;-)

2016-11-09 20:41 UTC, fbrnc commented on src/AwsInspector/Ssh/Connection.php
> +        if (count(explode(':', $configuration)) == 4) {
👍

2016-11-10 08:06 UTC, kj187 approved these changes
I would prefer $configurationData instead of $configurationArray, but its just nit-picking ;-)

Approved

2016-11-10 08:22 UTC, merged